# <font color="#ff9900"> **NumPy Básico - Exercícios**</font>
---

Este é um pequeno conjunto de exercícios para testar sua compreensão sobre alguns recursos básicos da biblioteca ``NumPy`` (https://numpy.org/). 

NumPy é um pacote fundamental para computação científica com Python, sendo uma biblioteca bastante madura otimizada para manipular *arrays* multidimensionais gigantes. Seu desenvolvimento é comunitário e possui licença BSD.
.

---

> 💡 **Observação**: Leia o exercício e insira as instruções necessárias para completar a tarefa na célula de código correspondente, isto é, aquelas marcadas com `` []``. Se necessário use como referência a saída esperada.  Para executar a célula de código, posicione dentro dela e pressione ``Ctrl``+``Enter``.

---

Antes de mais nada vamos importar NumPy e verificar a versão disponível.

In [ ]:
import numpy as np
np.__version__

'1.21.6'

1) **Dados dois** ***arrays* numpy $a$ e $b$ de dimensões similares, obtenha como saída um array $c$ no qual cada elemento é o resultado da soma elemento-a-elemento dos dois *arrays* inicias.**

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[2, 3, 4],
              [5, 6, 7]])

print(f" Array a:\n{a}\n\n Array b:\n{b}")


#  insira sua resposta
c = a + b
print(f"\n\n Array c:\n{c}")

 Array a:
[[1 2 3]
 [4 5 6]]

 Array b:
[[2 3 4]
 [5 6 7]]


 Array c:
[[ 3  5  7]
 [ 9 11 13]]


2) **Gere uma sequência numérica variando de $0$ a $100$ (inclusive) espaçada de $3$ números**.

In [ ]:
a = np.arange(0, 101, 3)
print(a)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


3) **Crie um *array* $3\times5$ para representar uma imagem totalmente branca, isto é, todos os pixels valendo $255$:**


In [ ]:
img = np.full((5,3),255)
print(img)

[[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]]


4) **Crie um *array* $3\times5$ para representar uma imagem totalmente preta, isto é, todos os pixels valendo $0$:**


In [ ]:
img = np.full((5,3),0)
print(img)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]



5) **Dados os *arrays* $a = \begin{bmatrix} -1 & 2 & 3 \\ 5 & 2 & 0 \end{bmatrix}$ e $b = \begin{bmatrix} 7 & 2 \\ 0 & 5 \\ 4 & 3 \end{bmatrix}$** efetue $c = a \cdot b$.
Dica: operador $@$ e função ```matmul```.


In [ ]:
a = np.array([[-1, 2, 3],
              [5, 2, 0]])

b = np.array([[7, 2],
              [0, 5],
              [4, 3]])

c = a @ b
print(c)

[[ 5 17]
 [35 20]]


6) **Apresente a transposta da matriz identidade $a_{3 \times 3}$. Dica: função ```np.eye```**


In [ ]:
a = np.eye(3)
a
# sua resposta
a_t = np.array(a).T
a_t

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7) **Crie um *array* dado um comprimento $length$, um valor inicial $start$ e o passo $step$**

```python
length = 10
start = 3
step = 2

#array([3,  5,  7,  9, 11, 13, 15, 17, 19, 21]) 
```

In [ ]:
length = 10
start = 3
step = 2

# sua resposta
np.arange(start, start + length*step, step)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

8) **Dado o array $x$, compute e apresente o valor máximo de cada linha.**



In [ ]:
np.random.seed(50)
x = np.random.randint(1, 20, size=(8, 3))
x
# sua resposta
x.max(axis=-1)

array([17, 14,  7, 14, 16, 15, 18, 10])

9)<img src="https://drive.google.com/uc?id=1CFPpZphJaaGNS9rTZKS5wurnkOX0JCbU" width="100" height="auto">  **O repositório da UCI oferece o *iris data set* (https://archive.ics.uci.edu/ml/datasets/iris) que contém características da planta íris (*Iris sp.*).  Dado o *dataset* ```sepallength``` que contém o atributo de comprimento das sépalas, calcule a média, a mediana e o desvio-padrão.**



In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

sepallength

# sua resposta
media = sepallength.mean()
mediana = np.median(sepallength)
desvio = sepallength.std()


print(f" Média:{media}\n\n Mediana:{mediana}\n\n Desvio-padrão:{desvio}")

 Média:5.843333333333334

 Mediana:5.8

 Desvio-padrão:0.8253012917851409


10) **Dado o *array* $a$ utilize a função ```np.where``` para gerar uma máscara de índices que obtenha todos os valores entre 5 e 10**



In [ ]:
np.random.seed(100)
a = np.random.randint(1, 25, [10,10])
a
# sua resposta
np.where(((a>=5)  & (a<=10)), True, False)

array([[ True, False,  True, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [ True, False, False, False,  True, False, False, False, False,
         True],
       [ True, False,  True, False, False, False, False, False,  True,
        False],
       [False,  True, False, False, False, False, False, False, False,
         True],
       [False,  True, False, False, False, False, False, False, False,
         True],
       [False, False, False, False,  True, False,  True, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False,  True,
         True],
       [ True,  True, False, False, False, False, False, False, False,
        False]])

11) ** Dado o array  $a_{10 \times 10}$  utilize indexação para obter apenas os números ímpares.**

In [ ]:
np.random.seed(10)
a = np.random.randint(1, 100, size=(10, 10))
a
# sua resposta
a[(a%2)!=0] 


array([65, 29,  9,  1, 41, 37, 17, 55, 89, 63, 73, 79, 55, 93, 87, 31, 31,
       13, 37, 19, 23, 95, 29, 75, 89, 19, 81, 89, 47, 29, 85, 97, 89, 45,
        5, 89, 89, 51, 55, 35, 89,  7, 23, 13, 93, 97, 63, 43, 51, 41,  1,
       19])

12) **Dado o *array*  $a_{10 \times 10}$  utilize indexação substituir todos os valores pares para 0.**

In [ ]:
np.random.seed(100)
a = np.random.randint(1, 100, size=(10, 10))
a
# sua resposta
a[np.mod(a,2)==0] = 0 
print(a)

[[ 9 25  0  0  0 49 11 95 53 99]
 [ 0 67 99 15 35 25  0 61 59 17]
 [ 0  0 87  3  0  5  0  0  0  0]
 [ 5  0  0  0  0  0  0  0  0 15]
 [ 0  0 81  3 95  0 99  0  0  0]
 [57 31 49  0  0 39 45 19 65 57]
 [35  0 75  0 73  0 31  0  0 69]
 [51  0  0  0  0 79  1  0  0 77]
 [ 0 71  0 85  0 11  0 61  0 49]
 [53  0 37  0  0 39 87 95 99 43]]


13) **Dado o *array*  $a_{1 \times 50}$  converta para um array  $a_{5 \times 10}$.**

In [ ]:
np.random.seed(10)
a = np.random.randint(1, 100, (1, 50))

print(f'a.shape: {a.shape} \n a:\n{a}')

# sua resposta
b = a.reshape(5, 10) 

print(f'b.shape: {b.shape} \n b:\n{b}')


a.shape: (1, 50) 
 a:
[[10 16 65 29 90 94 30  9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78
  70 14 26 14 93 87 31 31 90 13 66 32 58 37 28 19 94 78 23 24 95 12 29 75
  89 10]]
b.shape: (5, 10) 
 b:
[[10 16 65 29 90 94 30  9 74  1]
 [41 37 17 12 55 89 63 34 73 79]
 [50 52 55 78 70 14 26 14 93 87]
 [31 31 90 13 66 32 58 37 28 19]
 [94 78 23 24 95 12 29 75 89 10]]


---
<font color="#ffb31a">Fabio Alexandre **SPANHOL**</font> <faspanhol@gmail.com>

<font color="#cccccc">*Updated: aug 21 2022*</font>