<a href="https://colab.research.google.com/github/dev-marcos/Digital-image-processing/blob/main/Python%20Training/NumPy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color="#ff9900"> **NumPy Básico - Exercícios**</font>
---

Este é um pequeno conjunto de exercícios para testar sua compreensão sobre alguns recursos básicos da biblioteca ``NumPy`` (https://numpy.org/). 

NumPy é um pacote fundamental para computação científica com Python, sendo uma biblioteca bastante madura otimizada para manipular *arrays* multidimensionais gigantes. Seu desenvolvimento é comunitário e possui licença BSD.
.

---

> 💡 **Observação**: Leia o exercício e insira as instruções necessárias para completar a tarefa na célula de código correspondente, isto é, aquelas marcadas com `` []``. Se necessário use como referência a saída esperada.  Para executar a célula de código, posicione dentro dela e pressione ``Ctrl``+``Enter``.

---

Antes de mais nada vamos importar NumPy e verificar a versão disponível.

In [ ]:
import numpy as np
np.__version__

'1.21.6'

1) **Dados dois** ***arrays* numpy $a$ e $b$ de dimensões similares, obtenha como saída um array $c$ no qual cada elemento é o resultado da soma elemento-a-elemento dos dois *arrays* inicias.**

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[2, 3, 4],
              [5, 6, 7]])

print(f" Array a:\n{a}\n\n Array b:\n{b}")

#  insira sua resposta

 Array a:
[[1 2 3]
 [4 5 6]]

 Array b:
[[2 3 4]
 [5 6 7]]


2) **Gere uma sequência numérica variando de $0$ a $100$ (inclusive) espaçada de $3$ números**.

3) **Crie um *array* $3\times5$ para representar uma imagem totalmente branca, isto é, todos os pixels valendo $255$:**


4) **Crie um *array* $3\times5$ para representar uma imagem totalmente preta, isto é, todos os pixels valendo $0$:**



5) **Dados os *arrays* $a = \begin{bmatrix} -1 & 2 & 3 \\ 5 & 2 & 0 \end{bmatrix}$ e $b = \begin{bmatrix} 7 & 2 \\ 0 & 5 \\ 4 & 3 \end{bmatrix}$** efetue $c = a \cdot b$.
Dica: operador $@$ e função ```matmul```.


6) **Apresente a transposta da matriz identidade $a_{3 \times 3}$. Dica: função ```np.eye```**


In [ ]:
a = np.eye(3)
a
# sua resposta

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7) **Crie um *array* dado um comprimento $length$, um valor inicial $start$ e o passo $step$**

```python
length = 10
start = 3
step = 2

#array([3,  5,  7,  9, 11, 13, 15, 17, 19, 21]) 
```

In [ ]:
length = 10
start = 3
step = 2

# sua resposta

8) **Dado o array $x$, compute e apresente o valor máximo de cada linha.**



In [ ]:
np.random.seed(50)
x = np.random.randint(1, 20, size=(8, 3))
x
# sua resposta

array([[17,  1, 12],
       [14,  2,  5],
       [ 7,  6,  7],
       [14,  6,  3],
       [ 8, 16,  5],
       [15,  4,  7],
       [12, 18, 11],
       [10,  1,  7]])

9)<img src="https://drive.google.com/uc?id=1CFPpZphJaaGNS9rTZKS5wurnkOX0JCbU" width="100" height="auto">  **O repositório da UCI oferece o *iris data set* (https://archive.ics.uci.edu/ml/datasets/iris) que contém características da planta íris (*Iris sp.*).  Dado o *dataset* ```sepallength``` que contém o atributo de comprimento das sépalas, calcule a média, a mediana e o desvio-padrão.**



In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

sepallength

# sua resposta

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

10) **Dado o *array* $a$ utilize a função ```np.where``` para gerar uma máscara de índices que obtenha todos os valores entre 5 e 10**



In [ ]:
np.random.seed(100)
a = np.random.randint(1, 25, [10,10])
a
# sua resposta


array([ 9,  8,  5, 10,  5,  5,  5,  8,  8, 10,  8,  7,  9,  5,  9,  7, 10,
        5,  6,  8,  7])

11) ** Dado o array  $a_{10 \times 10}$  utilize indexação para obter apenas os números ímpares.**

In [ ]:
np.random.seed(10)
a = np.random.randint(1, 100, size=(10, 10))
a
# sua resposta

array([[10, 16, 65, 29, 90, 94, 30,  9, 74,  1],
       [41, 37, 17, 12, 55, 89, 63, 34, 73, 79],
       [50, 52, 55, 78, 70, 14, 26, 14, 93, 87],
       [31, 31, 90, 13, 66, 32, 58, 37, 28, 19],
       [94, 78, 23, 24, 95, 12, 29, 75, 89, 10],
       [16, 19, 81, 72, 89, 12, 18, 47,  8, 76],
       [29, 34, 85, 97, 89, 45,  6,  5, 72, 89],
       [89, 51, 55, 35, 16, 78, 89, 16,  7, 86],
       [23, 12, 13, 93, 97, 63, 58, 80, 43, 58],
       [98, 51, 46, 41, 90, 74, 38,  1, 19, 24]])

12) **Dado o *array*  $a_{10 \times 10}$  utilize indexação substituir todos os valores pares para 0.**

In [ ]:
np.random.seed(100)
a = np.random.randint(1, 100, size=(10, 10))
a
# sua resposta

array([[ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35, 25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28,  5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8, 50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95, 20, 99, 64, 54, 28],
       [57, 31, 49, 48, 40, 39, 45, 19, 65, 57],
       [35, 54, 75, 18, 73, 14, 31, 18, 54, 69],
       [51, 92, 92, 84, 54, 79,  1, 14, 58, 77],
       [ 4, 71,  4, 85, 80, 11, 88, 61,  4, 49],
       [53, 44, 37,  6, 72, 39, 87, 95, 99, 43]])

13) **Dado o *array*  $a_{1 \times 50}$  converta para um array  $a_{5 \times 10}$.**

In [ ]:
np.random.seed(10)
a = np.random.randint(1, 100, (1, 50))

print(f'a.shape: {a.shape} \n a:\n{a}')

# sua resposta

a.shape: (1, 50) 
 a:
[[10 16 65 29 90 94 30  9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78
  70 14 26 14 93 87 31 31 90 13 66 32 58 37 28 19 94 78 23 24 95 12 29 75
  89 10]]


---
<font color="#ffb31a">Fabio Alexandre **SPANHOL**</font> <faspanhol@gmail.com>

<font color="#cccccc">*Updated: aug 21 2022*</font>